### ISSUE TITLE
broken example in readme and no documentation

### ISSUE THREAD

**Issue by funkycode** [codefresh-io/go-sdk#1]
Hi,

The example in README is broken:
1) import is incorrect - it should be utils and not util
2) Codefresh New() func accepts &clientOptions and not AuthOptions.

Some more examples and documentation would be helpful

**Comment by olegsu** [comment]
Hey @funkycode 0506f4ae6527af700abea52a3e92b2eec4f5ebf0 fixed it

**Comment by funkycode** [comment]
not really.
First of all **ReadAuthContext** return two values, so it should be at least:
_options, _ := utils.ReadAuthContext(path, "")_
But anyway the code would not work, as options is not correct type for New() of client.
Also Pipelines() is not part of interface Codefresh (maybe part of codefresh struct), so GetPipelines() should be used instead.

I'll pull request the working example in few minutes

**Comment by olegsu** [comment]
The first part is completely correct, the func `ReadAuthContext` returns two value, this need to be fixed.
The second part is correct, we broke the api here 439ebf93a83e4fb169a64afc0dfc2034be54cc13 to make it more stardard.

**Comment by funkycode** [comment]
i made a pull request.
I see I was poking 0.5.0 at thursday and this what worked for me.
Now I see the changes, I would suggest to cherry pick those.
Also other suggestion, try to keep backward compatibility maybe at least few versions (use placeholders for deleted functions that would link to new ones + warning message to stdout/stderr of deprecation and suggestion to what should be switched) and state what would be broken deprecated in new version in changelog. Otherwise it would be hard for those who use sdk for own solutions to maintain/update their solutions based on the changes.

**Comment by olegsu** [comment]
Thanks for the feedback and the PR.
As for the backward compatibility, as the project is still in alpha phase I hope to keep it clean as I can. Means that til version 1.0.0 it would not follow semantic versioning.
Notes about breaking changes should and will be added to make it all clear.
