### ISSUE TITLE
Support for filtering pipelines by a given tag

### ISSUE THREAD

**Issue by pchico83** [codefresh-io/go-sdk#6]
I want to list only the pipelines having a given tag.
The pipeline list method does not support filtering by tags.

**Comment by olegsu** [comment]
@pchico83 the pipeline API support it using labels. For example, if your pipeline has tag `service` using the API would look like: `https://g.codefresh.io/api/pipelines?labels[tags]=service` and using Codefresh CLI would look like `codefresh get pipeline -l tags=service`

**Comment by pchico83** [comment]
@olegsu thanks. I made it work!
I will send a PR later
